/**
 * Converts the small Playwright selector subset emitted by AIVane recordings
 * into a serializable locator plan understood by the extension DOM helper.
 *
 * This intentionally does not attempt to implement Playwright's full selector
 * language. It covers the forms generated by the AIVane recorder:
 *   - `css >> nth=N`
 *   - `css:visible`
 *   - `text=value`
 *   - `css:has-text("value") descendant`
 */
export function normalizeDomLocator(value) {
  const source = locatorSource(value);
  let selector = source.value.trim();
  let index = source.index;

  const nth = selector.match(/\s*>>\s*nth\s*=\s*(-?\d+)\s*$/i);
  if (nth) {
    index = Number(nth[1]);
    selector = selector.slice(0, nth.index).trim();
  }

  if (source.strategy === "xpath") {
    return {
      strategy: "xpath",
      value: selector,
      index
    };
  }

  if (/^text\s*=/i.test(selector)) {
    const text = selector.replace(/^text\s*=/i, "").trim();
    const quoted = readQuotedText(text);
    return {
      strategy: "text",
      value: quoted.value,
      exact: quoted.quoted,
      visibleOnly: true,
      index
    };
  }

  const visibleOnly = selector.includes(":visible");
  selector = selector.replaceAll(":visible", "");

  // `:text-is()` is the exact counterpart of `:has-text()`. A substring match
  // cannot tell a result row apart from the "search for ..." row above it,
  // because the second one contains the text of the first.
  const textIs = readHasText(selector, ":text-is(");
  if (textIs) {
    return {
      strategy: "css",
      value: textIs.ancestorSelector || "*",
      hasText: textIs.text,
      exact: true,
      descendantSelector: textIs.descendantSelector || null,
      visibleOnly,
      index
    };
  }

  const hasText = readHasText(selector);
  if (hasText) {
    return {
      strategy: "css",
      value: hasText.ancestorSelector || "*",
      hasText: hasText.text,
      descendantSelector: hasText.descendantSelector || null,
      visibleOnly,
      index
    };
  }

  return {
    strategy: "css",
    value: selector.trim(),
    visibleOnly,
    index
  };
}

function locatorSource(value) {
  if (typeof value === "string") {
    return {
      strategy: inferStrategy(value),
      value: requireNonEmpty(value, "selector"),
      index: 0
    };
  }
  if (!value || typeof value !== "object") {
    throw selectorError("locator must be a selector string or locator object.");
  }
  const rawValue = requireNonEmpty(
    value.value ?? value.selector,
    "locator.value"
  );
  const rawIndex = value.index == null ? 0 : Number(value.index);
  if (!Number.isInteger(rawIndex)) {
    throw selectorError("locator.index must be an integer.");
  }
  const requested = String(value.strategy || inferStrategy(rawValue)).toLowerCase();
  const strategy = requested === "xpath" ? "xpath" : "css";
  return {
    strategy,
    value: rawValue,
    index: rawIndex
  };
}

function inferStrategy(value) {
  const normalized = String(value || "").trim();
  return (
    normalized.startsWith("xpath=") ||
    normalized.startsWith("//") ||
    normalized.startsWith("(//")
  ) ? "xpath" : "css";
}

function readQuotedText(value) {
  if (value.length >= 2) {
    const quote = value[0];
    if ((quote === "'" || quote === "\"") && value.at(-1) === quote) {
      return {
        quoted: true,
        value: unescapeQuoted(value.slice(1, -1), quote)
      };
    }
  }
  return { quoted: false, value };
}

function readHasText(selector, marker = ":has-text(") {
  const start = selector.indexOf(marker);
  if (start < 0) {
    return null;
  }
  let cursor = start + marker.length;
  while (/\s/.test(selector[cursor] || "")) {
    cursor += 1;
  }
  const quote = selector[cursor];
  if (quote !== "'" && quote !== "\"") {
    throw selectorError(`${marker}) requires a quoted text value.`);
  }
  cursor += 1;
  let text = "";
  let escaped = false;
  for (; cursor < selector.length; cursor += 1) {
    const character = selector[cursor];
    if (escaped) {
      text += character;
      escaped = false;
    } else if (character === "\\") {
      escaped = true;
    } else if (character === quote) {
      break;
    } else {
      text += character;
    }
  }
  if (cursor >= selector.length) {
    throw selectorError(`${marker}) contains an unterminated string.`);
  }
  cursor += 1;
  while (/\s/.test(selector[cursor] || "")) {
    cursor += 1;
  }
  if (selector[cursor] !== ")") {
    throw selectorError(`${marker}) is missing its closing parenthesis.`);
  }
  return {
    ancestorSelector: selector.slice(0, start).trim(),
    text,
    descendantSelector: selector.slice(cursor + 1).trim()
  };
}

function unescapeQuoted(value, quote) {
  return value
    .replaceAll(`\\${quote}`, quote)
    .replaceAll("\\\\", "\\");
}

function requireNonEmpty(value, name) {
  if (typeof value !== "string" || value.trim() === "") {
    throw selectorError(`${name} must be a non-empty string.`);
  }
  return value;
}

function selectorError(message) {
  const error = new Error(message);
  error.code = "UNSUPPORTED_SELECTOR";
  return error;
}
